// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using AzureCards.ConsoleClient.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace AzureCards.ConsoleClient.Models
{
    public partial class DealResponseMessage
    {
        private IList<Card> _cards;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<Card> Cards
        {
            get { return this._cards; }
            set { this._cards = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DealResponseMessage class.
        /// </summary>
        public DealResponseMessage()
        {
            this.Cards = new LazyList<Card>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken cardsSequence = ((JToken)inputObject["Cards"]);
                if (cardsSequence != null && cardsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken cardsValue in ((JArray)cardsSequence))
                    {
                        Card card = new Card();
                        card.DeserializeJson(cardsValue);
                        this.Cards.Add(card);
                    }
                }
            }
        }
    }
}
